AREA_ELEMENTS = {
    "kitchen": [
        {
            "node_id": "fridge_01",
            "name": "冰箱",
            "center": (0.75, 1.45),
            "size": (0.80, 1.55),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "window_kitchen_01",
            "name": "厨房窗户",
            "center": (1.85, 0.45),
            "size": (1.35, 0.20),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "sink_01",
            "name": "水槽",
            "center": (1.75, 1.45),
            "size": (1.15, 0.70),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "cabinet_kitchen_01",
            "name": "水槽下橱柜",
            "center": (1.70, 2.05),
            "size": (1.35, 0.55),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "microwave_01",
            "name": "微波炉",
            "center": (3.00, 0.85),
            "size": (0.60, 0.45),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "rice_cooker_01",
            "name": "电饭煲",
            "center": (3.65, 0.85),
            "size": (0.45, 0.45),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "stove_01",
            "name": "灶台",
            "center": (3.05, 1.55),
            "size": (0.95, 0.60),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "pot_red_01",
            "name": "红色锅",
            "center": (2.75, 1.55),
            "size": (0.40, 0.40),
            "movable": True,
            "status": "regular",
        },
        {
            "node_id": "pan_01",
            "name": "平底锅",
            "center": (3.35, 1.60),
            "size": (0.45, 0.35),
            "movable": True,
            "status": "regular",
        },
        {
            "node_id": "counter_01",
            "name": "操作台",
            "center": (3.00, 2.35),
            "size": (1.20, 0.80),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "cutting_board_01",
            "name": "砧板",
            "center": (2.65, 2.25),
            "size": (0.45, 0.35),
            "movable": True,
            "status": "regular",
        },
        {
            "node_id": "dish_rack_01",
            "name": "碗碟架",
            "center": (3.85, 2.25),
            "size": (0.40, 0.60),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "trash_bin_kitchen_01",
            "name": "厨房垃圾桶",
            "center": (3.85, 3.00),
            "size": (0.45, 0.65),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "rug_kitchen_01",
            "name": "厨房地垫",
            "center": (1.90, 2.80),
            "size": (0.90, 0.45),
            "status": "regular",
            "movable": False,
        },
    ],
    "dining_room": [
        {
            "node_id": "dining_table_01",
            "name": "餐桌",
            "center": (5.10, 2.45),
            "size": (1.55, 1.30),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "dining_chair_01",
            "name": "餐椅上左",
            "center": (4.65, 1.75),
            "size": (0.45, 0.55),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "dining_chair_02",
            "name": "餐椅上右",
            "center": (5.55, 1.75),
            "size": (0.45, 0.55),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "dining_chair_03",
            "name": "餐椅下左",
            "center": (4.65, 3.15),
            "size": (0.45, 0.55),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "dining_chair_04",
            "name": "餐椅下右",
            "center": (5.55, 3.15),
            "size": (0.45, 0.55),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "vase_dining_01",
            "name": "餐桌花瓶",
            "center": (5.10, 2.45),
            "size": (0.30, 0.45),
            "movable": True,
            "status": "regular",
        },
        {
            "node_id": "clock_wall_01",
            "name": "墙钟",
            "center": (5.25, 0.85),
            "size": (0.45, 0.45),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "wall_art_dining_01",
            "name": "墙画",
            "center": (6.00, 1.20),
            "size": (0.45, 0.55),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "plant_dining_01",
            "name": "餐厅绿植",
            "center": (6.15, 2.05),
            "size": (0.45, 0.70),
            "status": "regular",
            "movable": False,
        },
    ],
    "bedroom": [
        {
            "node_id": "bed_01",
            "name": "床",
            "center": (8.25, 1.70),
            "size": (1.45, 2.20),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "pillow_01",
            "name": "枕头",
            "center": (8.25, 1.05),
            "size": (1.00, 0.45),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "bedside_table_01",
            "name": "床头柜",
            "center": (6.95, 1.50),
            "size": (0.60, 0.60),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "lamp_bedside_01",
            "name": "床头台灯",
            "center": (6.75, 1.20),
            "size": (0.35, 0.55),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "window_bedroom_01",
            "name": "卧室窗户",
            "center": (7.35, 0.40),
            "size": (1.20, 0.20),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "curtain_bedroom_01",
            "name": "窗帘",
            "center": (7.35, 0.60),
            "size": (1.40, 0.60),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "wall_art_bed_01",
            "name": "床头画",
            "center": (8.55, 0.55),
            "size": (0.55, 0.40),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "rug_round_01",
            "name": "圆形地毯",
            "center": (7.35, 2.80),
            "size": (1.00, 1.00),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "slippers_bedroom_01",
            "name": "卧室拖鞋",
            "center": (7.05, 3.20),
            "size": (0.45, 0.35),
            "movable": True,
            "status": "regular",
        },
        {
            "node_id": "wardrobe_01",
            "name": "衣柜",
            "center": (8.85, 3.05),
            "size": (0.55, 1.75),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "clothes_wardrobe_01",
            "name": "衣柜内衣物",
            "center": (8.65, 3.15),
            "size": (0.35, 1.00),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "desk_bedroom_01",
            "name": "书桌",
            "center": (7.65, 4.00),
            "size": (0.90, 0.60),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "chair_bedroom_01",
            "name": "椅子",
            "center": (6.95, 3.85),
            "size": (0.45, 0.55),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "mirror_01",
            "name": "立镜",
            "center": (7.45, 3.85),
            "size": (0.35, 1.00),
            "status": "regular",
            "movable": False,
        },
    ],
    "entryway": [
        {
            "node_id": "door_front_01",
            "name": "前门",
            "center": (1.00, 7.95),
            "size": (0.90, 1.00),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "doormat_01",
            "name": "门垫",
            "center": (1.00, 9.05),
            "size": (1.10, 0.50),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "shoe_cabinet_01",
            "name": "鞋柜 / 玄关柜",
            "center": (0.50, 5.80),
            "size": (0.50, 1.00),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "coat_rack_01",
            "name": "挂衣架",
            "center": (1.60, 4.80),
            "size": (0.70, 0.30),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "coat_01",
            "name": "外套",
            "center": (1.45, 5.00),
            "size": (0.40, 0.80),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "bag_hanging_01",
            "name": "挎包",
            "center": (1.85, 5.00),
            "size": (0.40, 0.60),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "umbrella_stand_01",
            "name": "雨伞架",
            "center": (0.45, 7.00),
            "size": (0.40, 0.60),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "slippers_entry_01",
            "name": "粉色拖鞋",
            "center": (1.45, 5.80),
            "size": (0.40, 0.30),
            "movable": True,
            "status": "regular",
        },
        {
            "node_id": "shoes_entry_01",
            "name": "黑色鞋子",
            "center": (1.30, 6.50),
            "size": (0.50, 0.40),
            "movable": True,
            "status": "regular",
        },
        {
            "node_id": "slippers_entry_02",
            "name": "门口粉色拖鞋",
            "center": (0.95, 7.45),
            "size": (0.50, 0.35),
            "movable": True,
            "status": "regular",
        },
        {
            "node_id": "parcel_box_01",
            "name": "快递纸箱",
            "center": (1.65, 7.20),
            "size": (0.60, 0.60),
            "movable": True,
            "status": "regular",
        },
        {
            "node_id": "backpack_01",
            "name": "背包",
            "center": (1.95, 7.50),
            "size": (0.45, 0.55),
            "movable": True,
            "status": "regular",
        },
        {
            "node_id": "entrance_step_01",
            "name": "入口台阶",
            "center": (1.05, 9.53),
            "size": (1.60, 0.40),
            "status": "regular",
            "movable": False,
        },
    ],
    "living_room": [
        {
            "node_id": "armchair_01",
            "name": "单人沙发",
            "center": (5.25, 5.85),
            "size": (0.90, 1.00),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "cushion_01",
            "name": "抱枕 1",
            "center": (5.15, 5.75),
            "size": (0.25, 0.25),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "cushion_02",
            "name": "抱枕 2",
            "center": (5.40, 5.75),
            "size": (0.25, 0.25),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "coffee_table_01",
            "name": "茶几",
            "center": (4.20, 6.75),
            "size": (1.00, 1.25),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "rug_living_01",
            "name": "客厅地毯",
            "center": (4.30, 6.90),
            "size": (3.40, 2.70),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "tv_01",
            "name": "电视",
            "center": (2.65, 6.65),
            "size": (0.25, 1.35),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "tv_stand_01",
            "name": "电视柜",
            "center": (2.55, 6.85),
            "size": (0.35, 1.20),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "floor_lamp_01",
            "name": "落地灯",
            "center": (2.80, 5.30),
            "size": (0.40, 0.90),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "plant_living_01",
            "name": "客厅大绿植",
            "center": (5.95, 5.55),
            "size": (0.55, 0.80),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "plant_living_02",
            "name": "客厅下方绿植",
            "center": (2.85, 8.25),
            "size": (0.50, 0.60),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "bookshelf_01",
            "name": "书柜",
            "center": (6.55, 6.25),
            "size": (0.60, 1.80),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "toy_box_01",
            "name": "玩具箱",
            "center": (6.55, 7.40),
            "size": (0.75, 0.75),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "toy_ball_01",
            "name": "玩具球",
            "center": (6.55, 7.25),
            "size": (0.35, 0.35),
            "movable": True,
            "status": "regular",
        },
        {
            "node_id": "pouf_01",
            "name": "黄色圆凳",
            "center": (5.45, 7.25),
            "size": (0.50, 0.50),
            "status": "regular",
            "movable": False,
        },
    ],
    "bathroom": [
        {
            "node_id": "toilet_01",
            "name": "马桶",
            "center": (7.50, 5.60),
            "size": (0.55, 0.80),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "sink_bath_01",
            "name": "洗手池",
            "center": (7.45, 5.10),
            "size": (0.65, 0.55),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "mirror_bath_01",
            "name": "镜子",
            "center": (7.45, 4.65),
            "size": (0.55, 0.60),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "shower_01",
            "name": "淋浴间",
            "center": (8.55, 5.35),
            "size": (0.75, 1.50),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "shower_head_01",
            "name": "花洒",
            "center": (8.85, 4.95),
            "size": (0.25, 0.60),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "bath_mat_01",
            "name": "浴垫",
            "center": (7.75, 6.70),
            "size": (0.90, 0.50),
            "movable": True,
            "status": "regular",
        },
        {
            "node_id": "washing_machine_01",
            "name": "洗衣机",
            "center": (8.60, 6.75),
            "size": (0.70, 0.55),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "laundry_basket_01",
            "name": "洗衣篮",
            "center": (8.85, 7.00),
            "size": (0.45, 0.45),
            "movable": True,
            "status": "regular",
        },
    ],
    "main_balcony": [
        {
            "node_id": "glass_door_balcony_01",
            "name": "阳台玻璃门",
            "center": (4.40, 8.72),
            "size": (2.00, 0.24),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "railing_main_balcony_01",
            "name": "主阳台栏杆",
            "center": (4.70, 9.68),
            "size": (4.55, 0.14),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "flower_pot_01",
            "name": "花盆 1",
            "center": (3.60, 9.45),
            "size": (0.45, 0.45),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "flower_pot_02",
            "name": "花盆 2",
            "center": (4.25, 9.45),
            "size": (0.45, 0.45),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "flower_pot_03",
            "name": "花盆 3",
            "center": (4.85, 9.45),
            "size": (0.45, 0.45),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "plant_balcony_01",
            "name": "阳台绿植",
            "center": (6.15, 9.45),
            "size": (0.45, 0.55),
            "status": "regular",
            "movable": False,
        },
    ],
    "utility_balcony": [
        {
            "node_id": "railing_utility_balcony_01",
            "name": "生活阳台栏杆",
            "center": (8.10, 9.68),
            "size": (1.90, 0.14),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "drying_rack_01",
            "name": "晾衣架",
            "center": (7.75, 8.35),
            "size": (1.30, 0.90),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "flower_box_01",
            "name": "花箱",
            "center": (7.75, 9.45),
            "size": (1.30, 0.45),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "mop_01",
            "name": "拖把",
            "center": (8.85, 8.70),
            "size": (0.25, 1.10),
            "movable": True,
            "status": "regular",
        },
        {
            "node_id": "bucket_01",
            "name": "水桶",
            "center": (8.75, 8.25),
            "size": (0.45, 0.45),
            "movable": True,
            "status": "regular",
        },
        {
            "node_id": "broom_01",
            "name": "扫把",
            "center": (8.55, 9.00),
            "size": (0.20, 1.00),
            "movable": True,
            "status": "regular",
        },
        {
            "node_id": "storage_box_01",
            "name": "收纳箱",
            "center": (8.70, 9.45),
            "size": (0.75, 0.45),
            "movable": True,
            "status": "regular",
        },
        {
            "node_id": "plant_corner_01",
            "name": "角落绿植",
            "center": (7.25, 8.00),
            "size": (0.35, 0.45),
            "status": "regular",
            "movable": False,
        },
    ],
}


HOME_BLOCKING_ELEMENT_IDS = {
    "fridge_01",
    "sink_01",
    "cabinet_kitchen_01",
    "microwave_01",
    "rice_cooker_01",
    "stove_01",
    "counter_01",
    "trash_bin_kitchen_01",
    "dining_table_01",
    "dining_chair_01",
    "dining_chair_02",
    "dining_chair_03",
    "dining_chair_04",
    "bed_01",
    "bedside_table_01",
    "wardrobe_01",
    "desk_bedroom_01",
    "chair_bedroom_01",
    "mirror_01",
    "door_front_01",
    "shoe_cabinet_01",
    "coat_rack_01",
    "umbrella_stand_01",
    "parcel_box_01",
    "backpack_01",
    "armchair_01",
    "coffee_table_01",
    "tv_01",
    "tv_stand_01",
    "floor_lamp_01",
    "bookshelf_01",
    "toy_box_01",
    "pouf_01",
    "toilet_01",
    "sink_bath_01",
    "shower_01",
    "washing_machine_01",
    "laundry_basket_01",
    "railing_main_balcony_01",
    "railing_utility_balcony_01",
    "drying_rack_01",
    "storage_box_01",
}
