AREA_ELEMENTS = {
    "kitchen": [
        {
            "node_id": "fridge_01",
            "name": "Refrigerator",
            "center": (0.75, 1.45),
            "size": (0.80, 1.55),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "window_kitchen_01",
            "name": "kitchen window",
            "center": (1.85, 0.45),
            "size": (1.35, 0.20),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "sink_01",
            "name": "Sink",
            "center": (1.75, 1.45),
            "size": (1.15, 0.70),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "cabinet_kitchen_01",
            "name": "under-sink cabinet",
            "center": (1.70, 2.05),
            "size": (1.35, 0.55),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "microwave_01",
            "name": "microwave oven",
            "center": (3.00, 0.85),
            "size": (0.60, 0.45),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "rice_cooker_01",
            "name": "rice cooker",
            "center": (3.65, 0.85),
            "size": (0.45, 0.45),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "stove_01",
            "name": "Stove",
            "center": (3.05, 1.55),
            "size": (0.95, 0.60),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "pot_red_01",
            "name": "red pot",
            "center": (2.75, 1.55),
            "size": (0.40, 0.40),
            "movable": True,
            "status": "regular",
        },
        {
            "node_id": "pan_01",
            "name": "frying pan",
            "center": (3.35, 1.60),
            "size": (0.45, 0.35),
            "movable": True,
            "status": "regular",
        },
        {
            "node_id": "counter_01",
            "name": "Workbench",
            "center": (3.00, 2.35),
            "size": (1.20, 0.80),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "cutting_board_01",
            "name": "Cutting board",
            "center": (2.65, 2.25),
            "size": (0.45, 0.35),
            "movable": True,
            "status": "regular",
        },
        {
            "node_id": "dish_rack_01",
            "name": "dish rack",
            "center": (3.85, 2.25),
            "size": (0.40, 0.60),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "trash_bin_kitchen_01",
            "name": "kitchen trash can",
            "center": (3.85, 3.00),
            "size": (0.45, 0.65),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "rug_kitchen_01",
            "name": "kitchen floor mat",
            "center": (1.90, 2.80),
            "size": (0.90, 0.45),
            "status": "regular",
            "movable": False,
        },
    ],
    "dining_room": [
        {
            "node_id": "dining_table_01",
            "name": "Dining table",
            "center": (5.10, 2.45),
            "size": (1.55, 1.30),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "dining_chair_01",
            "name": "left side of dining chair",
            "center": (4.65, 1.75),
            "size": (0.45, 0.55),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "dining_chair_02",
            "name": "right side of dining chair",
            "center": (5.55, 1.75),
            "size": (0.45, 0.55),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "dining_chair_03",
            "name": "under left side of dining chair",
            "center": (4.65, 3.15),
            "size": (0.45, 0.55),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "dining_chair_04",
            "name": "Right side under dining chair",
            "center": (5.55, 3.15),
            "size": (0.45, 0.55),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "vase_dining_01",
            "name": "Dining table vase",
            "center": (5.10, 2.45),
            "size": (0.30, 0.45),
            "movable": True,
            "status": "regular",
        },
        {
            "node_id": "clock_wall_01",
            "name": "Wall clock",
            "center": (5.25, 0.85),
            "size": (0.45, 0.45),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "wall_art_dining_01",
            "name": "Wall art",
            "center": (6.00, 1.20),
            "size": (0.45, 0.55),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "plant_dining_01",
            "name": "Dining room plant",
            "center": (6.15, 2.05),
            "size": (0.45, 0.70),
            "status": "regular",
            "movable": False,
        },
    ],
    "bedroom": [
        {
            "node_id": "bed_01",
            "name": "Bed",
            "center": (8.25, 1.70),
            "size": (1.45, 2.20),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "pillow_01",
            "name": "Pillow",
            "center": (8.25, 1.05),
            "size": (1.00, 0.45),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "bedside_table_01",
            "name": "Nightstand",
            "center": (6.95, 1.50),
            "size": (0.60, 0.60),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "lamp_bedside_01",
            "name": "Bedside lamp",
            "center": (6.75, 1.20),
            "size": (0.35, 0.55),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "window_bedroom_01",
            "name": "Bedroom window",
            "center": (7.35, 0.40),
            "size": (1.20, 0.20),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "curtain_bedroom_01",
            "name": "Curtains",
            "center": (7.35, 0.60),
            "size": (1.40, 0.60),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "wall_art_bed_01",
            "name": "Bedside picture",
            "center": (8.55, 0.55),
            "size": (0.55, 0.40),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "rug_round_01",
            "name": "Round carpet",
            "center": (7.35, 2.80),
            "size": (1.00, 1.00),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "slippers_bedroom_01",
            "name": "Bedroom slippers",
            "center": (7.05, 3.20),
            "size": (0.45, 0.35),
            "movable": True,
            "status": "regular",
        },
        {
            "node_id": "wardrobe_01",
            "name": "Wardrobe",
            "center": (8.85, 3.05),
            "size": (0.55, 1.75),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "clothes_wardrobe_01",
            "name": "Clothes in the wardrobe",
            "center": (8.65, 3.15),
            "size": (0.35, 1.00),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "desk_bedroom_01",
            "name": "Desk",
            "center": (7.65, 4.00),
            "size": (0.90, 0.60),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "chair_bedroom_01",
            "name": "Chair",
            "center": (6.95, 3.85),
            "size": (0.45, 0.55),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "mirror_01",
            "name": "Full-length mirror",
            "center": (7.45, 3.85),
            "size": (0.35, 1.00),
            "status": "regular",
            "movable": False,
        },
    ],
    "entryway": [
        {
            "node_id": "door_front_01",
            "name": "Front door",
            "center": (1.00, 7.95),
            "size": (0.90, 1.00),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "doormat_01",
            "name": "Doormat",
            "center": (1.00, 9.05),
            "size": (1.10, 0.50),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "shoe_cabinet_01",
            "name": "Shoe cabinet / Entryway cabinet",
            "center": (0.50, 5.80),
            "size": (0.50, 1.00),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "coat_rack_01",
            "name": "Coat rack",
            "center": (1.60, 4.80),
            "size": (0.70, 0.30),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "coat_01",
            "name": "Coat",
            "center": (1.45, 5.00),
            "size": (0.40, 0.80),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "bag_hanging_01",
            "name": "satchel",
            "center": (1.85, 5.00),
            "size": (0.40, 0.60),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "umbrella_stand_01",
            "name": "umbrella stand",
            "center": (0.45, 7.00),
            "size": (0.40, 0.60),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "slippers_entry_01",
            "name": "pink slippers",
            "center": (1.45, 5.80),
            "size": (0.40, 0.30),
            "movable": True,
            "status": "regular",
        },
        {
            "node_id": "shoes_entry_01",
            "name": "black shoes",
            "center": (1.30, 6.50),
            "size": (0.50, 0.40),
            "movable": True,
            "status": "regular",
        },
        {
            "node_id": "slippers_entry_02",
            "name": "pink slippers at the entrance",
            "center": (0.95, 7.45),
            "size": (0.50, 0.35),
            "movable": True,
            "status": "regular",
        },
        {
            "node_id": "parcel_box_01",
            "name": "express delivery cardboard box",
            "center": (1.65, 7.20),
            "size": (0.60, 0.60),
            "movable": True,
            "status": "regular",
        },
        {
            "node_id": "backpack_01",
            "name": "backpack",
            "center": (1.95, 7.50),
            "size": (0.45, 0.55),
            "movable": True,
            "status": "regular",
        },
        {
            "node_id": "entrance_step_01",
            "name": "entrance steps",
            "center": (1.05, 9.53),
            "size": (1.60, 0.40),
            "status": "regular",
            "movable": False,
        },
    ],
    "living_room": [
        {
            "node_id": "armchair_01",
            "name": "single sofa",
            "center": (5.25, 5.85),
            "size": (0.90, 1.00),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "cushion_01",
            "name": "throw pillow 1",
            "center": (5.15, 5.75),
            "size": (0.25, 0.25),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "cushion_02",
            "name": "throw pillow 2",
            "center": (5.40, 5.75),
            "size": (0.25, 0.25),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "coffee_table_01",
            "name": "coffee table",
            "center": (4.20, 6.75),
            "size": (1.00, 1.25),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "rug_living_01",
            "name": "living room carpet",
            "center": (4.30, 6.90),
            "size": (3.40, 2.70),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "tv_01",
            "name": "TV",
            "center": (2.65, 6.65),
            "size": (0.25, 1.35),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "tv_stand_01",
            "name": "TV cabinet",
            "center": (2.55, 6.85),
            "size": (0.35, 1.20),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "floor_lamp_01",
            "name": "floor lamp",
            "center": (2.80, 5.30),
            "size": (0.40, 0.90),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "plant_living_01",
            "name": "large living room plant",
            "center": (5.95, 5.55),
            "size": (0.55, 0.80),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "plant_living_02",
            "name": "lower living room plant",
            "center": (2.85, 8.25),
            "size": (0.50, 0.60),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "bookshelf_01",
            "name": "bookshelf",
            "center": (6.55, 6.25),
            "size": (0.60, 1.80),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "toy_box_01",
            "name": "toy box",
            "center": (6.55, 7.40),
            "size": (0.75, 0.75),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "toy_ball_01",
            "name": "toy ball",
            "center": (6.55, 7.25),
            "size": (0.35, 0.35),
            "movable": True,
            "status": "regular",
        },
        {
            "node_id": "pouf_01",
            "name": "yellow round stool",
            "center": (5.45, 7.25),
            "size": (0.50, 0.50),
            "status": "regular",
            "movable": False,
        },
    ],
    "bathroom": [
        {
            "node_id": "toilet_01",
            "name": "toilet",
            "center": (7.50, 5.60),
            "size": (0.55, 0.80),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "sink_bath_01",
            "name": "sink",
            "center": (7.45, 5.10),
            "size": (0.65, 0.55),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "mirror_bath_01",
            "name": "Mirror",
            "center": (7.45, 4.65),
            "size": (0.55, 0.60),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "shower_01",
            "name": "Shower stall",
            "center": (8.55, 5.35),
            "size": (0.75, 1.50),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "shower_head_01",
            "name": "Showerhead",
            "center": (8.85, 4.95),
            "size": (0.25, 0.60),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "bath_mat_01",
            "name": "Bath mat",
            "center": (7.75, 6.70),
            "size": (0.90, 0.50),
            "movable": True,
            "status": "regular",
        },
        {
            "node_id": "washing_machine_01",
            "name": "Washing machine",
            "center": (8.60, 6.75),
            "size": (0.70, 0.55),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "laundry_basket_01",
            "name": "Laundry basket",
            "center": (8.85, 7.00),
            "size": (0.45, 0.45),
            "movable": True,
            "status": "regular",
        },
    ],
    "main_balcony": [
        {
            "node_id": "glass_door_balcony_01",
            "name": "Balcony glass door",
            "center": (4.40, 8.72),
            "size": (2.00, 0.24),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "railing_main_balcony_01",
            "name": "Main balcony railing",
            "center": (4.70, 9.68),
            "size": (4.55, 0.14),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "flower_pot_01",
            "name": "Flower pot 1",
            "center": (3.60, 9.45),
            "size": (0.45, 0.45),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "flower_pot_02",
            "name": "Flower pot 2",
            "center": (4.25, 9.45),
            "size": (0.45, 0.45),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "flower_pot_03",
            "name": "Flower pot 3",
            "center": (4.85, 9.45),
            "size": (0.45, 0.45),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "plant_balcony_01",
            "name": "Balcony greenery",
            "center": (6.15, 9.45),
            "size": (0.45, 0.55),
            "status": "regular",
            "movable": False,
        },
    ],
    "utility_balcony": [
        {
            "node_id": "railing_utility_balcony_01",
            "name": "balcony railing",
            "center": (8.10, 9.68),
            "size": (1.90, 0.14),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "drying_rack_01",
            "name": "clothes drying rack",
            "center": (7.75, 8.35),
            "size": (1.30, 0.90),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "flower_box_01",
            "name": "flower box",
            "center": (7.75, 9.45),
            "size": (1.30, 0.45),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "mop_01",
            "name": "mop",
            "center": (8.85, 8.70),
            "size": (0.25, 1.10),
            "movable": True,
            "status": "regular",
        },
        {
            "node_id": "bucket_01",
            "name": "bucket",
            "center": (8.75, 8.25),
            "size": (0.45, 0.45),
            "movable": True,
            "status": "regular",
        },
        {
            "node_id": "broom_01",
            "name": "broom",
            "center": (8.55, 9.00),
            "size": (0.20, 1.00),
            "movable": True,
            "status": "regular",
        },
        {
            "node_id": "storage_box_01",
            "name": "storage box",
            "center": (8.70, 9.45),
            "size": (0.75, 0.45),
            "movable": True,
            "status": "regular",
        },
        {
            "node_id": "plant_corner_01",
            "name": "corner plant",
            "center": (7.25, 8.00),
            "size": (0.35, 0.45),
            "status": "regular",
            "movable": False,
        },
    ],
}


HOME_BLOCKING_ELEMENT_IDS = {
    "fridge_01",
    "sink_01",
    "cabinet_kitchen_01",
    "microwave_01",
    "rice_cooker_01",
    "stove_01",
    "counter_01",
    "trash_bin_kitchen_01",
    "dining_table_01",
    "dining_chair_01",
    "dining_chair_02",
    "dining_chair_03",
    "dining_chair_04",
    "bed_01",
    "bedside_table_01",
    "wardrobe_01",
    "desk_bedroom_01",
    "chair_bedroom_01",
    "mirror_01",
    "door_front_01",
    "shoe_cabinet_01",
    "coat_rack_01",
    "umbrella_stand_01",
    "parcel_box_01",
    "backpack_01",
    "armchair_01",
    "coffee_table_01",
    "tv_01",
    "tv_stand_01",
    "floor_lamp_01",
    "bookshelf_01",
    "toy_box_01",
    "pouf_01",
    "toilet_01",
    "sink_bath_01",
    "shower_01",
    "washing_machine_01",
    "laundry_basket_01",
    "railing_main_balcony_01",
    "railing_utility_balcony_01",
    "drying_rack_01",
    "storage_box_01",
}
