AREA_ELEMENTS = {
    "entryway": [
        {
            "node_id": "office_front_door_01",
            "name": "办公室入口门",
            "center": (1.30, 9.68),
            "size": (1.25, 0.16),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "coat_hook_rack_01",
            "name": "挂衣钩",
            "center": (0.58, 7.30),
            "size": (0.18, 1.00),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "coat_01",
            "name": "外套",
            "center": (0.66, 7.25),
            "size": (0.28, 0.70),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "bag_01",
            "name": "手提包",
            "center": (0.92, 7.55),
            "size": (0.35, 0.35),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "shoe_bench_01",
            "name": "鞋柜",
            "center": (1.00, 8.85),
            "size": (1.05, 0.55),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "entry_mat_01",
            "name": "入口地垫",
            "center": (1.45, 7.85),
            "size": (0.95, 0.55),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "umbrella_stand_01",
            "name": "雨伞桶",
            "center": (2.05, 8.55),
            "size": (0.35, 0.45),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "entry_plant_01",
            "name": "入口绿植",
            "center": (0.62, 9.10),
            "size": (0.45, 0.55),
            "status": "regular",
            "movable": False,
        },
    ],
    "lounge_area": [
        {
            "node_id": "lounge_armchair_01",
            "name": "绿色单人沙发",
            "center": (1.35, 4.40),
            "size": (0.90, 0.90),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "side_table_lounge_01",
            "name": "沙发旁圆桌",
            "center": (0.78, 5.05),
            "size": (0.58, 0.58),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "table_lamp_lounge_01",
            "name": "接待区台灯",
            "center": (0.72, 4.92),
            "size": (0.25, 0.25),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "mug_lounge_01",
            "name": "沙发旁马克杯",
            "center": (0.88, 5.18),
            "size": (0.18, 0.18),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "lounge_rug_01",
            "name": "接待区地毯",
            "center": (1.85, 4.55),
            "size": (1.95, 1.65),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "large_floor_plant_01",
            "name": "接待区大型绿植",
            "center": (0.72, 5.75),
            "size": (0.55, 0.55),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "wall_picture_left_01",
            "name": "左墙挂画",
            "center": (0.28, 3.70),
            "size": (0.16, 0.70),
            "status": "regular",
            "movable": False,
        },
    ],
    "storage_archive_area": [
        {
            "node_id": "bookshelf_left_01",
            "name": "文件书柜",
            "center": (1.15, 1.25),
            "size": (1.20, 1.45),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "file_binders_left_01",
            "name": "书柜文件夹",
            "center": (1.25, 1.10),
            "size": (0.75, 0.28),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "storage_boxes_left_01",
            "name": "蓝色收纳盒",
            "center": (2.55, 1.28),
            "size": (0.60, 0.45),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "trophy_left_01",
            "name": "奖杯",
            "center": (1.85, 0.88),
            "size": (0.25, 0.25),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "photo_frame_left_01",
            "name": "书柜相框",
            "center": (1.75, 0.62),
            "size": (0.24, 0.30),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "certificate_wall_01",
            "name": "墙上证书",
            "center": (2.55, 0.72),
            "size": (0.45, 0.55),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "drawer_cabinet_left_01",
            "name": "左侧抽屉柜",
            "center": (2.65, 1.85),
            "size": (0.68, 0.72),
            "status": "regular",
            "movable": False,
        },
    ],
    "main_workspace": [
        {
            "node_id": "office_desk_01",
            "name": "主办公桌",
            "center": (5.25, 3.10),
            "size": (2.35, 1.05),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "office_chair_01",
            "name": "办公椅",
            "center": (5.20, 2.05),
            "size": (0.75, 0.75),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "desktop_monitor_01",
            "name": "显示器",
            "center": (5.50, 2.82),
            "size": (0.65, 0.20),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "keyboard_01",
            "name": "键盘",
            "center": (5.18, 3.10),
            "size": (0.55, 0.18),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "mouse_01",
            "name": "鼠标",
            "center": (5.70, 3.12),
            "size": (0.18, 0.14),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "desk_lamp_01",
            "name": "办公桌台灯",
            "center": (6.25, 2.72),
            "size": (0.30, 0.30),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "pen_holder_01",
            "name": "笔筒",
            "center": (4.72, 3.00),
            "size": (0.22, 0.22),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "notebook_desk_01",
            "name": "桌面笔记本",
            "center": (4.50, 3.45),
            "size": (0.42, 0.32),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "document_tray_desk_01",
            "name": "桌面文件盘",
            "center": (6.05, 3.45),
            "size": (0.45, 0.35),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "desk_plant_01",
            "name": "办公桌小绿植",
            "center": (4.20, 2.70),
            "size": (0.30, 0.30),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "window_back_01",
            "name": "后墙窗户",
            "center": (5.10, 0.48),
            "size": (1.85, 0.22),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "window_plants_01",
            "name": "窗台植物",
            "center": (5.15, 1.08),
            "size": (0.75, 0.30),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "wall_clock_01",
            "name": "墙钟",
            "center": (6.72, 0.95),
            "size": (0.42, 0.42),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "workspace_floor_plant_01",
            "name": "办公区落地植物",
            "center": (6.95, 1.90),
            "size": (0.55, 0.65),
            "status": "regular",
            "movable": False,
        },
    ],
    "print_supply_area": [
        {
            "node_id": "printer_copier_01",
            "name": "打印复印机",
            "center": (8.45, 1.45),
            "size": (0.85, 0.70),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "printer_cabinet_01",
            "name": "打印机下柜",
            "center": (8.45, 2.25),
            "size": (0.78, 0.62),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "paper_stack_01",
            "name": "打印纸",
            "center": (8.55, 1.02),
            "size": (0.35, 0.25),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "side_storage_cabinet_01",
            "name": "右侧矮柜",
            "center": (8.35, 3.55),
            "size": (0.95, 0.72),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "inbox_tray_01",
            "name": "文件收纳盘",
            "center": (8.10, 3.20),
            "size": (0.40, 0.30),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "wall_board_01",
            "name": "办公公告板",
            "center": (9.30, 3.05),
            "size": (0.16, 1.05),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "wall_picture_right_01",
            "name": "右墙挂画",
            "center": (9.28, 2.00),
            "size": (0.15, 0.70),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "print_area_plant_01",
            "name": "打印区绿植",
            "center": (7.55, 1.15),
            "size": (0.45, 0.55),
            "status": "regular",
            "movable": False,
        },
    ],
    "meeting_area": [
        {
            "node_id": "meeting_table_01",
            "name": "小会谈桌",
            "center": (5.25, 5.80),
            "size": (1.25, 1.00),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "meeting_chair_left_01",
            "name": "左侧会谈椅",
            "center": (4.22, 5.82),
            "size": (0.55, 0.65),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "meeting_chair_right_01",
            "name": "右侧会谈椅",
            "center": (6.28, 5.82),
            "size": (0.55, 0.65),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "meeting_rug_01",
            "name": "会谈区地毯",
            "center": (5.25, 5.90),
            "size": (2.40, 1.55),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "mug_meeting_01",
            "name": "会谈桌马克杯",
            "center": (4.95, 5.70),
            "size": (0.18, 0.18),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "plant_meeting_01",
            "name": "会谈桌小植物",
            "center": (5.28, 5.58),
            "size": (0.25, 0.25),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "tablet_meeting_01",
            "name": "会谈桌平板",
            "center": (5.68, 5.95),
            "size": (0.42, 0.30),
            "status": "regular",
            "movable": True,
        },
    ],
    "pantry_area": [
        {
            "node_id": "mini_fridge_01",
            "name": "小冰箱",
            "center": (4.10, 8.35),
            "size": (0.75, 0.95),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "plant_on_fridge_01",
            "name": "冰箱上的植物",
            "center": (4.10, 7.78),
            "size": (0.35, 0.35),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "pantry_counter_01",
            "name": "茶水柜",
            "center": (5.65, 8.35),
            "size": (1.55, 0.72),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "microwave_01",
            "name": "微波炉",
            "center": (5.20, 8.08),
            "size": (0.45, 0.32),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "coffee_machine_01",
            "name": "咖啡机",
            "center": (5.92, 8.02),
            "size": (0.38, 0.38),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "mug_pantry_01",
            "name": "茶水区杯子",
            "center": (5.42, 8.70),
            "size": (0.20, 0.20),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "cups_shelf_01",
            "name": "杯具架",
            "center": (5.78, 8.72),
            "size": (0.45, 0.24),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "snack_bag_01",
            "name": "零食袋",
            "center": (6.35, 8.20),
            "size": (0.26, 0.32),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "storage_jars_01",
            "name": "食品罐",
            "center": (6.22, 8.72),
            "size": (0.42, 0.22),
            "status": "regular",
            "movable": True,
        },
    ],
    "bathroom": [
        {
            "node_id": "toilet_01",
            "name": "马桶",
            "center": (7.85, 7.65),
            "size": (0.55, 0.75),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "sink_bathroom_01",
            "name": "卫生间洗手池",
            "center": (8.68, 7.72),
            "size": (0.62, 0.50),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "mirror_bathroom_01",
            "name": "卫生间镜子",
            "center": (8.68, 7.12),
            "size": (0.48, 0.12),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "soap_dispenser_01",
            "name": "洗手液",
            "center": (8.98, 7.55),
            "size": (0.14, 0.18),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "trash_bin_bathroom_01",
            "name": "卫生间垃圾桶",
            "center": (8.95, 8.78),
            "size": (0.36, 0.40),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "bathroom_mat_01",
            "name": "卫生间地垫",
            "center": (8.20, 8.85),
            "size": (0.85, 0.52),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "toilet_paper_holder_01",
            "name": "纸巾架",
            "center": (7.42, 8.12),
            "size": (0.16, 0.28),
            "status": "regular",
            "movable": False,
        },
    ],
}


OFFICE_BLOCKING_ELEMENT_IDS = {
    "office_front_door_01",
    "coat_hook_rack_01",
    "shoe_bench_01",
    "umbrella_stand_01",
    "entry_plant_01",
    "lounge_armchair_01",
    "side_table_lounge_01",
    "large_floor_plant_01",
    "bookshelf_left_01",
    "drawer_cabinet_left_01",
    "office_desk_01",
    "office_chair_01",
    "desktop_monitor_01",
    "window_back_01",
    "window_plants_01",
    "wall_clock_01",
    "workspace_floor_plant_01",
    "printer_copier_01",
    "printer_cabinet_01",
    "side_storage_cabinet_01",
    "wall_board_01",
    "print_area_plant_01",
    "meeting_table_01",
    "meeting_chair_left_01",
    "meeting_chair_right_01",
    "mini_fridge_01",
    "pantry_counter_01",
    "microwave_01",
    "coffee_machine_01",
    "cups_shelf_01",
    "toilet_01",
    "sink_bathroom_01",
    "trash_bin_bathroom_01",
    "toilet_paper_holder_01",
}
