"""Configuration shared by Desire update callers."""

DESIRE_UPDATE_ON_INTENT_END = "intent_end"
DESIRE_UPDATE_EVERY_STEP = "every_step"
DESIRE_UPDATE_MODES = (
    DESIRE_UPDATE_ON_INTENT_END,
    DESIRE_UPDATE_EVERY_STEP,
)
DEFAULT_DESIRE_UPDATE_MODE = DESIRE_UPDATE_EVERY_STEP
