# Permanent furniture geometry is projected from Unity snapshot
# scene_20260814_151128_342: 2D (x, y) = Unity (x + 11.268, z + 6.350).
# Physical footprints exclude interaction_point and setting_area helpers.
AREA_ELEMENTS = {
    "bedroom": [
        {
            "node_id": "bedroom_bed_01",
            "name": "Bedroom Bed",
            "center": (1.384, 9.180),
            "size": (2.252, 1.807),
            "movable": False,
        },
        {
            "node_id": "bedroom_rug_01",
            "name": "Bedroom Carpet",
            "center": (2.04, 9.22),
            "size": (2.38, 2.63),
            "movable": False,
            "blocks_movement": False,
            "physical_status": "slightly_messy",
            "state_details": {"surface_state": "wrinkled"},
        },
        {
            "node_id": "bedside_table_left_01",
            "name": "Left Bedroom Nightstand",
            "center": (0.49, 7.96),
            "size": (0.38, 0.46),
            "movable": False,
        },
        {
            "node_id": "bedside_table_right_01",
            "name": "Right Bedroom Nightstand",
            "center": (0.49, 10.48),
            "size": (0.38, 0.46),
            "movable": False,
        },
        {
            "node_id": "bedroom_kettle_01",
            "name": "Bedroom Kettle",
            "semantic_type": "water_container",
            "center": (0.72, 5.68),
            "size": (0.24, 0.20),
            "movable": True,
            "blocks_movement": False,
            "state_details": {
                "location": "on_computer_desk",
                "support_element_id": "bedroom_computer_desk_01",
                "contains": "water",
            },
        },
        {
            "node_id": "bedroom_water_cup_01",
            "name": "Bedroom Water Cup",
            "semantic_type": "cup",
            "center": (0.72, 5.24),
            "size": (0.18, 0.18),
            "movable": True,
            "blocks_movement": False,
            "state_details": {
                "location": "on_computer_desk",
                "support_element_id": "bedroom_computer_desk_01",
                "contains": "half_water",
            },
        },
        {
            "node_id": "bedroom_computer_desk_01",
            "name": "Bedroom Computer Desk",
            "center": (0.604, 5.319),
            "size": (0.740, 1.523),
            "movable": False,
        },
        {
            "node_id": "bedroom_computer_01",
            "name": "computer",
            "center": (0.554, 5.273),
            "size": (0.578, 0.641),
            "movable": False,
            "blocks_movement": False,
            "interaction_status": "in_use",
            "state_details": {"power_state": "on", "screen_state": "desktop"},
        },
        {
            "node_id": "gaming_chair_01",
            "name": "gaming chair",
            "center": (1.556, 5.274),
            "size": (0.762, 0.766),
            "movable": True,
            "physical_status": "slightly_moved",
        },
        {
            "node_id": "bedroom_wardrobe_01",
            "name": "bedroom cabinet",
            "center": (5.456, 9.165),
            "size": (0.400, 1.820),
            "movable": False,
            "state_details": {"door_state": "closed"},
        },
        {
            "node_id": "bedroom_curtain_01",
            "name": "bedroom curtain",
            "center": (2.97, 11.90),
            "size": (5.12, 0.35),
            "movable": False,
            "blocks_movement": False,
            "state_details": {"curtain_state": "closed"},
        },
        {
            "node_id": "bedroom_door_01",
            "name": "Bedroom Door",
            "center": (5.81, 6.92),
            "size": (0.35, 1.16),
            "movable": False,
            "state_details": {"door_state": "open"},
        },
    ],
    "bathroom": [
        {
            "node_id": "toilet_01",
            "name": "toilet",
            "center": (6.193, 3.596),
            "size": (0.726, 0.462),
            "movable": False,
        },
        {
            "node_id": "laundry_basket_01",
            "name": "laundry basket",
            "center": (10.10, 1.20),
            "size": (0.52, 0.52),
            "movable": True,
            "blocks_movement": False,
            "physical_status": "slightly_messy",
            "state_details": {"contains": "dirty_clothes"},
        },
        {
            "node_id": "bath_towel_01",
            "name": "bath towel",
            "center": (5.875, 3.612),
            "size": (0.102, 0.704),
            "movable": True,
        },
        {
            "node_id": "towel_rack_01",
            "name": "towel rack",
            "center": (11.70, 3.70),
            "size": (0.65, 0.18),
            "movable": False,
            "blocks_movement": False,
        },
        {
            "node_id": "hand_towel_01",
            "name": "towel",
            "center": (11.84, 3.60),
            "size": (0.32, 0.22),
            "movable": True,
            "blocks_movement": False,
            "physical_status": "used",
            "state_details": {
                "location": "on_vanity",
                "support_element_id": "bathroom_vanity_01",
                "wet_state": "damp",
            },
        },
        {
            "node_id": "bathtub_01",
            "name": "bathtub",
            "center": (8.441, 0.881),
            "size": (1.920, 0.928),
            "movable": False,
            "state_details": {"water_state": "empty"},
        },
        {
            "node_id": "bathroom_curtain_01",
            "name": "bathroom curtain",
            "center": (9.71, 0.38),
            "size": (1.49, 0.35),
            "movable": False,
            "blocks_movement": False,
            "state_details": {"curtain_state": "closed"},
        },
        {
            "node_id": "washing_machine_01",
            "name": "Washing machine",
            "center": (10.897, 0.987),
            "size": (0.731, 0.798),
            "movable": False,
            "state_details": {"door_state": "closed", "power_state": "off"},
        },
        {
            "node_id": "bathroom_vanity_01",
            "name": "vanity sink",
            "center": (11.976, 3.104),
            "size": (0.600, 2.141),
            "movable": False,
            "physical_status": "slightly_dirty",
            "state_details": {"faucet_state": "off", "surface_state": "water_spots"},
        },
        {
            "node_id": "bathroom_mirror_01",
            "name": "vanity mirror",
            "semantic_type": "mirror",
            "center": (12.227, 3.094),
            "size": (0.040, 1.960),
            "movable": False,
            "blocks_movement": False,
            "physical_status": "slightly_dirty",
            "state_details": {"surface_state": "smudged"},
        },
        {
            "node_id": "toothbrush_cup_01",
            "name": "Toothbrush cup",
            "center": (11.88, 3.20),
            "size": (0.18, 0.18),
            "movable": True,
            "blocks_movement": False,
            "state_details": {
                "location": "on_vanity",
                "support_element_id": "bathroom_vanity_01",
            },
        },
        {
            "node_id": "toothbrush_01",
            "name": "Toothbrush",
            "center": (11.88, 3.20),
            "size": (0.22, 0.06),
            "movable": True,
            "blocks_movement": False,
            "state_details": {
                "location": "in_toothbrush_cup",
                "support_element_id": "toothbrush_cup_01",
            },
        },
        {
            "node_id": "bathroom_broom_01",
            "name": "broom",
            "center": (11.95, 4.80),
            "size": (0.18, 0.85),
            "movable": True,
            "blocks_movement": False,
            "state_details": {"location": "near_bathroom_wall"},
        },
        {
            "node_id": "shower_room_01",
            "name": "Shower stall",
            "center": (6.55, 1.60),
            "size": (1.00, 1.00),
            "movable": False,
            "blocks_movement": False,
            "state_details": {"door_state": "open", "water_state": "empty"},
        },
        {
            "node_id": "shower_head_01",
            "name": "Showerhead",
            "center": (6.159, 1.600),
            "size": (0.20, 0.20),
            "movable": False,
            "blocks_movement": False,
            "state_details": {"flow_state": "off", "temperature": "unset"},
        },
        {
            "node_id": "bathroom_door_01",
            "name": "Bathroom door",
            "center": (9.70, 5.60),
            "size": (1.14, 0.35),
            "movable": False,
            "state_details": {"door_state": "open"},
        },
    ],
    "living_room": [
        {
            "node_id": "living_bookshelf_01",
            "name": "Living room bookshelf",
            "center": (7.385, 5.815),
            "size": (3.094, 0.337),
            "movable": False,
            "state_details": {"contains": "books"},
        },
        {
            "node_id": "side_table_01",
            "name": "Sofa side table",
            "center": (6.417, 9.459),
            "size": (0.677, 0.677),
            "movable": False,
            "physical_status": "slightly_messy",
            "state_details": {"surface_state": "has_small_items"},
        },
        {
            "node_id": "living_sofa_01",
            "name": "Large living room sofa",
            "center": (6.879, 11.859),
            "size": (1.920, 4.181),
            "movable": False,
        },
        {
            "node_id": "living_rug_01",
            "name": "living room carpet",
            "center": (7.60, 11.59),
            "size": (3.45, 5.19),
            "movable": False,
            "blocks_movement": False,
        },
        {
            "node_id": "coffee_table_01",
            "name": "Living room coffee table",
            "center": (8.388, 11.741),
            "size": (0.784, 1.475),
            "movable": False,
        },
        {
            "node_id": "coffee_table_remote_01",
            "name": "TV remote control",
            "semantic_type": "remote_control",
            "center": (8.30, 11.35),
            "size": (0.26, 0.12),
            "movable": True,
            "blocks_movement": False,
            "physical_status": "misplaced",
            "state_details": {
                "location": "near_edge_of_coffee_table",
                "support_element_id": "coffee_table_01",
            },
        },
        {
            "node_id": "coffee_table_cup_01",
            "name": "Cup on the coffee table",
            "semantic_type": "cup",
            "center": (8.55, 11.55),
            "size": (0.20, 0.20),
            "movable": True,
            "blocks_movement": False,
            "state_details": {
                "location": "on_coffee_table",
                "support_element_id": "coffee_table_01",
                "contains": "half_water",
            },
        },
        {
            "node_id": "coffee_table_fruit_plate_01",
            "name": "Fruit plate on the coffee table",
            "center": (8.18, 12.05),
            "size": (0.42, 0.32),
            "movable": True,
            "blocks_movement": False,
            "state_details": {
                "location": "on_coffee_table",
                "support_element_id": "coffee_table_01",
                "contains": "fruit",
            },
        },
        {
            "node_id": "living_tv_cabinet_01",
            "name": "Living room TV cabinet",
            "center": (12.079, 11.595),
            "size": (0.293, 2.770),
            "movable": False,
        },
        {
            "node_id": "tv_01",
            "name": "TV",
            "center": (12.177, 11.607),
            "size": (0.027, 2.113),
            "movable": False,
            "blocks_movement": False,
            "state_details": {"power_state": "off"},
        },
        {
            "node_id": "living_curtain_01",
            "name": "Living room curtains",
            "center": (9.18, 14.34),
            "size": (5.12, 0.35),
            "movable": False,
            "blocks_movement": False,
            "state_details": {"curtain_state": "half_open"},
        },
        {
            "node_id": "living_flower_pot_01",
            "name": "Living Room Flower Pot",
            "center": (10.72, 13.82),
            "size": (0.38, 0.38),
            "movable": True,
            "blocks_movement": False,
            "state_details": {"location": "near_window", "plant_state": "slightly_dry"},
        },
        {
            "node_id": "watering_can_01",
            "name": "Watering Can",
            "semantic_type": "water_container",
            "center": (11.16, 13.82),
            "size": (0.32, 0.24),
            "movable": True,
            "blocks_movement": False,
            "state_details": {
                "location": "near_flower_pot",
                "support_element_id": "living_flower_pot_01",
                "contains": "water",
            },
        },
    ],
    "kitchen": [
        {
            "node_id": "kitchen_door_01",
            "name": "Kitchen Door",
            "center": (12.36, 6.64),
            "size": (0.35, 1.12),
            "movable": False,
            "state_details": {"door_state": "open"},
        },
        {
            "node_id": "built_in_cabinet_01",
            "name": "Built-in Cabinet",
            "center": (12.890, 5.042),
            "size": (0.810, 1.679),
            "movable": False,
            "state_details": {"door_state": "closed"},
        },
        {
            "node_id": "fridge_01",
            "name": "Refrigerator",
            "center": (12.991, 5.278),
            "size": (0.963, 0.950),
            "movable": False,
            "blocks_movement": False,
            "state_details": {"door_state": "closed", "contains": "food_and_drinks"},
        },
        {
            "node_id": "dishwasher_01",
            "name": "Dishwasher",
            "center": (12.907, 4.526),
            "size": (0.518, 0.629),
            "movable": False,
            "blocks_movement": False,
            "state_details": {"door_state": "closed", "power_state": "off"},
        },
        {
            "node_id": "oven_01",
            "name": "Oven",
            "center": (12.881, 4.527),
            "size": (0.560, 0.629),
            "movable": False,
            "blocks_movement": False,
            "state_details": {"door_state": "closed", "power_state": "off"},
        },
        {
            "node_id": "range_hood_01",
            "name": "Range Hood",
            "center": (12.763, 2.291),
            "size": (0.582, 1.186),
            "movable": False,
            "blocks_movement": False,
            "state_details": {"power_state": "off"},
        },
        {
            "node_id": "kitchen_counter_window_01",
            "name": "Kitchen L-Shaped Counter Window Section",
            "center": (14.448, 0.656),
            "size": (3.917, 0.570),
            "movable": False,
        },
        {
            "node_id": "kitchen_counter_side_01",
            "name": "Kitchen L-Shaped Counter Side Section",
            "center": (12.846, 2.281),
            "size": (0.759, 3.862),
            "movable": False,
        },
        {
            "node_id": "kitchen_sink_01",
            "name": "Kitchen Sink",
            "semantic_type": "sink",
            "components": ["faucet", "basin"],
            "center": (14.448, 0.682),
            "size": (0.70, 0.40),
            "movable": False,
            "blocks_movement": False,
            "physical_status": "slightly_wet",
            "state_details": {"faucet_state": "off", "basin_state": "wet"},
        },
        {
            "node_id": "stove_01",
            "name": "Stove",
            "center": (12.759, 2.350),
            "size": (0.506, 0.916),
            "movable": False,
            "blocks_movement": False,
            "state_details": {"power_state": "off"},
        },
        {
            "node_id": "frying_pan_01",
            "name": "frying pan",
            "semantic_type": "cookware",
            "center": (12.759, 2.350),
            "size": (0.42, 0.42),
            "movable": True,
            "blocks_movement": False,
            "state_details": {
                "location": "on_stove",
                "support_element_id": "stove_01",
                "contains": "empty",
                "surface_state": "clean",
                "temperature": "room_temperature",
            },
        },
        {
            "node_id": "spatula_01",
            "name": "Spatula",
            "semantic_type": "cooking_utensil",
            "center": (12.846, 1.470),
            "size": (0.36, 0.09),
            "movable": True,
            "blocks_movement": False,
            "state_details": {
                "location": "on_kitchen_counter",
                "support_element_id": "kitchen_counter_side_01",
                "clean_state": "clean",
            },
        },
        {
            "node_id": "kitchen_table_01",
            "name": "Kitchen Dining Table",
            "center": (16.056, 4.456),
            "size": (0.748, 2.995),
            "movable": False,
        },
        {
            "node_id": "kitchen_cup_01",
            "name": "Kitchen Cup",
            "semantic_type": "cup",
            "center": (15.88, 3.35),
            "size": (0.20, 0.20),
            "movable": True,
            "blocks_movement": False,
            "state_details": {
                "location": "on_kitchen_table",
                "support_element_id": "kitchen_table_01",
                "contains": "empty",
                "clean_state": "clean",
            },
        },
        {
            "node_id": "kitchen_plate_01",
            "name": "Kitchen Plate 1",
            "center": (16.10, 4.00),
            "size": (0.30, 0.30),
            "movable": True,
            "blocks_movement": False,
            "state_details": {
                "location": "on_kitchen_table",
                "support_element_id": "kitchen_table_01",
            },
        },
        {
            "node_id": "kitchen_plate_02",
            "name": "Kitchen Plate 2",
            "center": (16.10, 4.35),
            "size": (0.30, 0.30),
            "movable": True,
            "blocks_movement": False,
            "physical_status": "used",
            "state_details": {
                "location": "on_kitchen_table",
                "support_element_id": "kitchen_table_01",
                "clean_state": "dirty",
            },
        },
        {
            "node_id": "kitchen_plate_03",
            "name": "Kitchen Plate 3",
            "center": (16.10, 4.70),
            "size": (0.30, 0.30),
            "movable": True,
            "blocks_movement": False,
            "state_details": {
                "location": "on_kitchen_table",
                "support_element_id": "kitchen_table_01",
            },
        },
        {
            "node_id": "kitchen_cutlery_01",
            "name": "Cutlery Set",
            "center": (15.84, 4.35),
            "size": (0.30, 0.12),
            "movable": True,
            "blocks_movement": False,
            "state_details": {
                "location": "on_kitchen_table",
                "support_element_id": "kitchen_table_01",
            },
        },
        {
            "node_id": "coffee_machine_01",
            "name": "Coffee machine",
            "semantic_type": "coffee_machine",
            "center": (15.90, 0.67),
            "size": (0.48, 0.38),
            "movable": True,
            "blocks_movement": False,
            "interaction_status": "standby",
            "state_details": {
                "location": "on_kitchen_counter",
                "support_element_id": "kitchen_counter_window_01",
                "power_state": "standby",
            },
        },
        {
            "node_id": "cutting_board_01",
            "name": "Cutting board",
            "center": (14.92, 0.68),
            "size": (0.55, 0.35),
            "movable": True,
            "blocks_movement": False,
            "physical_status": "used",
            "state_details": {
                "location": "on_kitchen_counter",
                "support_element_id": "kitchen_counter_window_01",
                "surface_state": "food_residue",
            },
        },
        {
            "node_id": "kitchen_knife_01",
            "name": "Chef's Knife",
            "center": (14.95, 0.68),
            "size": (0.32, 0.08),
            "movable": True,
            "blocks_movement": False,
            "state_details": {
                "location": "on_cutting_board",
                "support_element_id": "cutting_board_01",
            },
        },
        {
            "node_id": "seasoning_bottle_01",
            "name": "Spice Jar",
            "center": (13.45, 0.67),
            "size": (0.18, 0.18),
            "movable": True,
            "blocks_movement": False,
            "state_details": {
                "location": "on_kitchen_counter",
                "support_element_id": "kitchen_counter_window_01",
                "contains": "seasoning",
            },
        },
        {
            "node_id": "kitchen_rag_01",
            "name": "Dishcloth",
            "center": (15.86, 5.35),
            "size": (0.28, 0.18),
            "movable": True,
            "blocks_movement": False,
            "physical_status": "used",
            "state_details": {
                "location": "on_kitchen_table",
                "support_element_id": "kitchen_table_01",
                "clean_state": "damp",
            },
        },
        {
            "node_id": "kitchen_fruit_01",
            "name": "Fruit on the Kitchen Table",
            "center": (16.10, 3.60),
            "size": (0.32, 0.28),
            "movable": True,
            "blocks_movement": False,
            "state_details": {
                "location": "on_kitchen_table",
                "support_element_id": "kitchen_table_01",
                "edible_state": "fresh",
            },
        },
        {
            "node_id": "bottled_water_01",
            "name": "Bottled Water",
            "semantic_type": "water_container",
            "center": (15.86, 5.05),
            "size": (0.16, 0.28),
            "movable": True,
            "blocks_movement": False,
            "state_details": {
                "location": "on_kitchen_table",
                "support_element_id": "kitchen_table_01",
                "contains": "water",
            },
        },
        {
            "node_id": "table_milk_01",
            "name": "Milk",
            "center": (16.14, 5.05),
            "size": (0.20, 0.28),
            "movable": True,
            "blocks_movement": False,
            "state_details": {
                "location": "on_kitchen_table",
                "support_element_id": "kitchen_table_01",
                "contains": "milk",
            },
        },
        {
            "node_id": "salmon_01",
            "name": "Salmon",
            "semantic_type": "fish",
            "center": (16.08, 5.55),
            "size": (0.38, 0.22),
            "movable": True,
            "blocks_movement": False,
            "state_details": {
                "location": "on_kitchen_table",
                "support_element_id": "kitchen_table_01",
                "edible_state": "raw",
            },
        },
        {
            "node_id": "kitchen_chair_01",
            "name": "Kitchen Chair 1",
            "center": (17.008, 4.940),
            "size": (0.998, 0.998),
            "movable": True,
        },
        {
            "node_id": "kitchen_chair_02",
            "name": "Kitchen Chair 2",
            "center": (17.063, 3.680),
            "size": (0.998, 0.998),
            "movable": True,
        },
        {
            "node_id": "kitchen_chair_03",
            "name": "Kitchen Chair 3",
            "center": (15.238, 4.725),
            "size": (0.998, 0.998),
            "movable": True,
        },
        {
            "node_id": "kitchen_chair_04",
            "name": "Kitchen Chair 4",
            "center": (15.238, 3.670),
            "size": (0.998, 0.998),
            "movable": True,
        },
        {
            "node_id": "kitchen_curtain_01",
            "name": "Kitchen Curtain",
            "center": (15.52, 0.36),
            "size": (2.36, 0.35),
            "movable": False,
            "blocks_movement": False,
            "state_details": {"curtain_state": "closed"},
        },
        {
            "node_id": "trash_can_01",
            "name": "Trash Can",
            "center": (15.272, 7.499),
            "size": (0.293, 0.293),
            "movable": False,
            "state_details": {"contains": "trash"},
        },
    ],
}


UNITY_HOME_BLOCKING_ELEMENT_IDS = {
    "bedroom_bed_01",
    "bedside_table_left_01",
    "bedside_table_right_01",
    "bedroom_computer_desk_01",
    "gaming_chair_01",
    "bedroom_wardrobe_01",
    "toilet_01",
    "bathtub_01",
    "washing_machine_01",
    "bathroom_vanity_01",
    "living_bookshelf_01",
    "side_table_01",
    "living_sofa_01",
    "coffee_table_01",
    "living_tv_cabinet_01",
    "built_in_cabinet_01",
    "kitchen_counter_window_01",
    "kitchen_counter_side_01",
    "kitchen_table_01",
    "kitchen_chair_01",
    "kitchen_chair_02",
    "kitchen_chair_03",
    "kitchen_chair_04",
    "trash_can_01",
}
