from __future__ import annotations

import json


def build_agent_body_state_update_prompt(
    *,
    agent_name: str,
    action_proposal: str,
    world_action_event: dict | None = None,
    agent_node: dict,
    current_agent_fact_edges: list[dict],
    context_facts: list[str],
) -> str:
    event_json = json.dumps(world_action_event or {}, ensure_ascii=False, indent=2)
    agent_node_json = json.dumps(agent_node, ensure_ascii=False, indent=2)
    current_agent_fact_edges_json = json.dumps(current_agent_fact_edges, ensure_ascii=False, indent=2)
    context_facts_json = json.dumps(context_facts, ensure_ascii=False, indent=2)
    return f"""You are responsible for updating the human agent's own physical state in the simulation environment.

The agent action proposal is the body movement the agent just intended to perform.
The world_action_event is the actual event that has already occurred in this small step generated by the world; it is more authoritative than the action proposal.
The previous module has determined that this action does not require support from new environmental elements, nor does it need to change external elements.

Your task is to determine how the human agent node itself should change after this small step, based on the world_action_event, the current state of the human agent node, the currently valid agent fact relations, and context_facts.

Only the following fields of the human agent node are allowed to be updated:
- posture
- interaction_elements
- interaction_method
- gaze_target
- worn_items
- body_surface
- text_to_motion_description

By default, retain current external relations and current interaction_elements.
If the action proposal does not explicitly indicate stopping, leaving, putting down, or ending interaction, do not clear interaction_elements, nor imply that external relations have ended.
If a field has no explicit change, do not return this field.

body_surface uses short English states, for example:
dry_clean, wet_clean, wet_dirty, soapy, dirty, sweaty, dry_dirty

text_to_motion_description is special; it is used for the subsequent text2motion model and must describe a body process that can be converted into skeleton actions.
Requirements:
- Use English action descriptions, do not use Chinese.
- Do not write specific person names; use "a person" or directly write body actions.
- The granularity should be like: a person raises both arms, pulls off a jacket, lowers the arms, sits on the ground.
- Try to write body parts, directions, and continuous actions, for example raises, reaches, grasps, pulls, bends, lowers, turns, sits.
- Do not use uncertain expressions such as or, maybe, possibly, seems to; you must choose a specific action sequence.
- Do not only write results, such as "is clean" or "has finished washing", which are unqualified.
The feedback_hint is a natural language factual result for reference by the subsequent feedback module and must use {agent_name} as the subject.

Return only JSON that can be directly parsed by json.loads; do not explain the reasoning process.

Return format:
{{
  "agent_state_patch": {{
    "posture": "standing | sitting | lying | crouching, etc.",
    "interaction_elements": ["Retained or updated interaction node id"],
    "interaction_method": "Short Chinese action method",
    "gaze_target": "Gaze target node id or empty string",
    "worn_items": ["Worn items"],
    "body_surface": "dry_clean | wet_clean | wet_dirty | soapy | dirty | sweaty | dry_dirty",
    "text_to_motion_description": "English text2motion action sequence, no character name"
  }},
  "feedback_hint": "{agent_name} what actually happened."
}}

Examples:

action proposal: {agent_name} rubs body with foam.
If the current interaction_elements indicates that {agent_name} is interacting with the showerhead, then retain interaction_elements.
The return can include body_surface=soapy, interaction_method=rubbing body,
text_to_motion_description=a person raises both hands, rubs foam across the arms and torso, circles the hands over the body surface.

action proposal: {agent_name} rinses off the foam on the body.
If the current body_surface=soapy, return body_surface=wet_clean,
text_to_motion_description=a person stands under running water, turns the torso, moves both hands downward to rinse foam from the body.

action proposal: {agent_name} dries the body.
Return body_surface=dry_clean,
text_to_motion_description=a person holds a towel with both hands, wipes the arms and torso, bends slightly, and pats the body dry.

agent_node:
{agent_node_json}

current_agent_fact_edges:
{current_agent_fact_edges_json}

context_facts:
{context_facts_json}

world_action_event:
{event_json}

agent action proposal:
{action_proposal}
""".strip()
