from __future__ import annotations

import json


def build_world_relation_update_prompt(
    *,
    agent_name: str,
    action_proposal: str,
    world_action_event: dict | None = None,
    element_support_result: dict,
    agent_node: dict,
    relevant_nodes: list[dict],
    current_fact_edges: list[dict],
) -> str:
    event_json = json.dumps(world_action_event or {}, ensure_ascii=False, indent=2)
    support_json = json.dumps(element_support_result, ensure_ascii=False, indent=2)
    agent_node_json = json.dumps(agent_node, ensure_ascii=False, indent=2)
    relevant_nodes_json = json.dumps(relevant_nodes, ensure_ascii=False, indent=2)
    current_fact_edges_json = json.dumps(current_fact_edges, ensure_ascii=False, indent=2)

    return f"""You are responsible for updating the fact relations resulting from this small step in the simulation environment.

The agent's action proposal is merely "what it intends to do."
The world_action_event is the actual small-step event generated by the world; it is more authoritative than the action proposal.
The previous module has already determined which elements support this action and assigned any necessary temporary elements as referenceable nodes.
Your task is not to re-evaluate whether the action is feasible, nor to generate the next action.
Your task is to determine, based on the world_action_event, element support results, current nodes, and current fact relations, what happens after this small step actually occurs:
- Which fact relations need to be added
- Which old fact relations no longer hold and need to be removed
- How the human agent's physical state snapshot needs to be updated
- What factual feedback is returned to the agent

Only process fact relations.
Do not add, delete, or modify structural relations.
Do not add, delete, or modify affiliation relations.
The creation, ownership, and lifecycle of temporary elements have been handled by the previous layer; here you only need to express in the fact relations what is happening now between the temporary element and the agent/other elements.

Fact relations are facts in the current world.
For example:
{agent_name} --sitting_on--> green single sofa
{agent_name} --holding--> a book
{agent_name} --looking_at--> a book
{agent_name} --interacting_with--> desk
a book --placed_on--> main desk

If a new fact makes an old fact no longer hold, you must put the old fact into fact_edges_to_remove.
For example, if {agent_name} puts the book in hand onto the table, then {agent_name} --holding--> book no longer holds.
For example, if {agent_name} stands up from the sofa, then {agent_name} --sitting_on--> sofa no longer holds.
For example, if {agent_name} changes to looking at the desktop, then the old {agent_name} --looking_at--> other object no longer holds.

Do not over-infer unrelated facts.
For example, {agent_name} sitting down and picking up a pillow does not imply she necessarily put down the book or food in her hand; unless the action proposal explicitly says put down, throw away, eat, drink, switch hands, or element_support_result has already explicitly updated these temporary elements.

The state of the agent's own body surface, posture, gaze, and action descriptions should be written into agent_state_patch first.
Do not add a fact relation from the agent to itself just to express "body is wet" or "body has foam," unless this fact needs to form a relationship with some external element.

Relation names must use English snake_case; do not use Chinese relation names.
Recommended short relations include located_in, holding, sitting_on, standing_near, looking_at, interacting_with, placed_on, inside.
But subject_id and object_id must come from relevant_nodes or current fact_edges; do not make up IDs out of thin air.
The consumed, disposed, discarded lifecycle end states of temporary elements are already written in the node state; do not add new consumed/disposed-like fact relations.
fact_edges_to_remove can only remove triples that already exist in current_fact_edges; do not remove relationships that "theoretically should exist but are not currently listed."
For fact_edges_to_add, do not add two synonymous relations for the same fact simultaneously, e.g., do not add both holding and carried_by.
Even if the action does not require element interaction, you can still update agent_state_patch, e.g., posture, body_surface, gaze_target, text_to_motion_description.

agent_state_patch should only write fields that have clearly changed or are clearly confirmable after this step.
Available fields include:
posture, interaction_elements, interaction_method, gaze_target, worn_items, body_surface, text_to_motion_description

text_to_motion_description is for subsequent text2motion and must describe the bodily process that can be converted into skeleton actions.
Requirements:
- Use English action descriptions; do not use Chinese.
- Do not write {agent_name} or other specific names; use "a person" or directly write body actions.
- Granularity should be like: a person raises both arms, pulls off a jacket, lowers the arms, sits on the ground.
- Try to write body parts, directions, continuous actions, e.g., reaches, grasps, lifts, turns, bends, lowers, places, sits.
- If the action involves objects, you can write generalized objects like the object / a book / a cup; do not write character names.
- Do not use uncertain expressions like or, maybe, possibly, seems to; you must choose a specific action sequence.
- Do not only write results, e.g., "is holding a book", "is sitting" are unqualified.
- Do not write pre-placement, pathfinding, or walking to the target into text_to_motion_description; if world_action_event is opening the refrigerator, the action description should start from reaching out and grabbing the handle, not from walking towards the refrigerator.

feedback_narration is the factual feedback returned by the environment to the agent.
It must explicitly use {agent_name} as the subject.
Do not use "you" instead of {agent_name}.

Only return JSON that can be directly parsed by json.loads; do not explain the reasoning process, do not write comments.
If an array has no content, return an empty array []; do not write explanatory text in the array.

Return format:
{{
  "fact_edges_to_add": [
    {{
      "subject_id": "existing node id",
      "relation": "english_snake_case_relation",
      "object_id": "existing node id",
      "reason": "why this fact is added"
    }}
  ],
  "fact_edges_to_remove": [
    {{
      "subject_id": "existing node id",
      "relation": "english relation existing in current_fact_edges",
      "object_id": "existing node id",
      "reason": "why this old fact no longer holds"
    }}
  ],
  "agent_state_patch": {{
    "posture": "standing | sitting | lying | crouching etc.",
    "interaction_elements": ["node ids currently interacting"],
    "interaction_method": "short Chinese action method",
    "gaze_target": "gaze target node id or empty string",
    "worn_items": ["worn items"],
    "body_surface": "dry_clean | wet | dirty | soapy etc.",
    "text_to_motion_description": "English text2motion action sequence, no character name"
  }},
  "feedback_narration": "{agent_name} what actually happened."
}}

element_support_result:
{support_json}

world_action_event:
{event_json}

agent_node:
{agent_node_json}

relevant_nodes:
{relevant_nodes_json}

current_fact_edges:
{current_fact_edges_json}

agent action proposal:
{action_proposal}
""".strip()
