AREA_ELEMENTS = {
    "entrance_area": [
        {
            "node_id": "heavy_wooden_door",
            "name": "Thick arched wooden door",
            "center": (0.38, 1.55),
            "size": (0.34, 1.45),
            "status": "regular",
            "movable": False,
            "state_details": {"door_state": "closed"},
        },
        {
            "node_id": "door_hinge_bar",
            "name": "Black iron beam on the door",
            "center": (0.55, 1.55),
            "size": (0.16, 0.88),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "door_handle_lock",
            "name": "Door lock and handle",
            "center": (0.62, 1.70),
            "size": (0.14, 0.26),
            "status": "regular",
            "movable": False,
            "state_details": {"lock_state": "unlocked"},
        },
        {
            "node_id": "brass_nameplate",
            "name": "Brass door plaque",
            "center": (0.54, 0.78),
            "size": (0.20, 0.22),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "wall_lantern_entry",
            "name": "Entrance wall lamp",
            "center": (1.18, 0.68),
            "size": (0.22, 0.34),
            "status": "regular",
            "movable": False,
            "state_details": {"lantern_state": "off"},
        },
        {
            "node_id": "robe_rack",
            "name": "Robe rack",
            "center": (2.08, 1.42),
            "size": (0.58, 0.82),
            "status": "regular",
            "movable": False,
            "state_details": {"robe_state": "on_rack"},
        },
        {
            "node_id": "dark_teacher_robe",
            "name": "Dark teacher's robe",
            "center": (2.10, 1.58),
            "size": (0.42, 0.82),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "pointed_hat",
            "name": "Pointed hat",
            "center": (2.36, 0.92),
            "size": (0.26, 0.22),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "boots_pair",
            "name": "leather boots",
            "center": (2.12, 2.38),
            "size": (0.44, 0.30),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "umbrella_stand",
            "name": "umbrella stand",
            "center": (1.70, 1.72),
            "size": (0.34, 0.42),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "walking_stick",
            "name": "walking stick",
            "center": (1.78, 1.58),
            "size": (0.12, 0.62),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "entrance_rug",
            "name": "green entrance carpet",
            "center": (1.22, 2.48),
            "size": (1.20, 0.68),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "left_plant_stand",
            "name": "plant stand by the door",
            "center": (0.66, 0.88),
            "size": (0.42, 0.62),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "small_drawer_entry",
            "name": "small drawer cabinet at the entrance",
            "center": (2.62, 2.15),
            "size": (0.42, 0.64),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "visitor_note_board",
            "name": "message board at the entrance",
            "center": (2.55, 0.88),
            "size": (0.48, 0.58),
            "status": "regular",
            "movable": False,
            "state_details": {"visitor_note_state": "unread"},
        },
    ],
    "teacher_work_area": [
        {
            "node_id": "large_wooden_desk",
            "name": "large wooden desk",
            "center": (4.62, 3.08),
            "size": (2.35, 0.96),
            "status": "regular",
            "movable": False,
            "state_details": {"lesson_plan_state": "draft", "homework_state": "ungraded"},
        },
        {
            "node_id": "high_back_chair",
            "name": "high-back chair",
            "center": (4.55, 2.15),
            "size": (0.72, 0.76),
            "status": "regular",
            "movable": False,
            "state_details": {"chair_state": "empty"},
        },
        {
            "node_id": "desk_lantern",
            "name": "desk lantern",
            "center": (3.68, 2.85),
            "size": (0.24, 0.30),
            "status": "regular",
            "movable": True,
            "state_details": {"lantern_state": "off"},
        },
        {
            "node_id": "quill_pen",
            "name": "quill pen",
            "center": (3.92, 2.70),
            "size": (0.18, 0.42),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "ink_bottle",
            "name": "ink bottle",
            "center": (3.82, 3.02),
            "size": (0.16, 0.16),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "open_lesson_plan",
            "name": "Open Course Plan",
            "center": (4.66, 2.82),
            "size": (0.62, 0.44),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "parchment_stack",
            "name": "Pile of Parchment",
            "center": (4.42, 3.22),
            "size": (0.46, 0.32),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "rolled_scroll",
            "name": "Scroll",
            "center": (5.18, 2.88),
            "size": (0.38, 0.16),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "sealed_letter",
            "name": "Sealed Letter",
            "center": (5.52, 3.36),
            "size": (0.36, 0.22),
            "status": "regular",
            "movable": True,
            "state_details": {"letter_state": "sealed"},
        },
        {
            "node_id": "magic_books_stack",
            "name": "Pile of Magic Books",
            "center": (5.68, 2.52),
            "size": (0.46, 0.42),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "student_homework_stack",
            "name": "Pile of Student Assignments",
            "center": (5.74, 3.08),
            "size": (0.42, 0.34),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "wax_seal",
            "name": "Wax Seal",
            "center": (5.88, 3.38),
            "size": (0.18, 0.18),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "desk_drawer_left",
            "name": "Left Desk Drawer",
            "center": (3.76, 3.55),
            "size": (0.52, 0.38),
            "status": "regular",
            "movable": False,
            "state_details": {"drawer_state": "closed"},
        },
        {
            "node_id": "desk_drawer_right",
            "name": "Right Desk Drawer",
            "center": (5.82, 3.55),
            "size": (0.52, 0.38),
            "status": "regular",
            "movable": False,
            "state_details": {"drawer_state": "closed"},
        },
        {
            "node_id": "small_hourglass",
            "name": "Small Hourglass",
            "center": (3.52, 3.08),
            "size": (0.16, 0.24),
            "status": "regular",
            "movable": True,
        },
    ],
    "lore_display_area": [
        {
            "node_id": "gothic_window",
            "name": "Gothic Arched Window",
            "center": (6.98, 0.72),
            "size": (1.05, 0.30),
            "status": "regular",
            "movable": False,
            "state_details": {"window_state": "closed"},
        },
        {
            "node_id": "window_sill_plants",
            "name": "Windowsill plant",
            "center": (6.98, 1.14),
            "size": (0.72, 0.30),
            "status": "regular",
            "movable": False,
            "state_details": {"plant_state": "healthy"},
        },
        {
            "node_id": "potion_vials_window",
            "name": "Potion Bottle on Windowsill",
            "center": (7.36, 1.12),
            "size": (0.38, 0.24),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "potion_diagram_frame",
            "name": "Potion Codex",
            "center": (8.52, 0.92),
            "size": (0.62, 0.72),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "alchemy_symbol_chart",
            "name": "Alchemy Symbol Chart",
            "center": (8.42, 1.78),
            "size": (0.72, 0.74),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "curved_display_shelf",
            "name": "Upper Right Curved Display Shelf",
            "center": (8.04, 2.42),
            "size": (1.72, 0.70),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "brass_astrolabe",
            "name": "Brass Astrolabe",
            "center": (7.56, 2.28),
            "size": (0.45, 0.45),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "hanging_scale",
            "name": "Hanging Balance Scale",
            "center": (8.54, 2.78),
            "size": (0.50, 0.35),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "herb_bundle_hanging",
            "name": "Hanging Herb Bundle",
            "center": (8.95, 2.45),
            "size": (0.24, 0.52),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "display_potion_bottles",
            "name": "Display Potion Bottle Set",
            "center": (8.05, 2.56),
            "size": (0.75, 0.30),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "magical_potted_plant",
            "name": "Upper Right Magical Potted Plant",
            "center": (8.92, 1.14),
            "size": (0.44, 0.52),
            "status": "regular",
            "movable": False,
            "state_details": {"plant_state": "healthy"},
        },
        {
            "node_id": "candle_stand_wall",
            "name": "Wall-Side Candle",
            "center": (6.48, 1.50),
            "size": (0.18, 0.30),
            "status": "regular",
            "movable": True,
        },
    ],
    "student_consult_area": [
        {
            "node_id": "round_consult_table",
            "name": "Small Round Table",
            "center": (1.58, 4.72),
            "size": (1.10, 1.10),
            "status": "regular",
            "movable": False,
            "state_details": {"consultation_state": "not_started"},
        },
        {
            "node_id": "guest_chair_a",
            "name": "Visitor Chair A",
            "center": (1.04, 4.05),
            "size": (0.48, 0.58),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "guest_chair_b",
            "name": "Visitor Chair B",
            "center": (2.18, 4.18),
            "size": (0.48, 0.58),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "consultation_candle",
            "name": "Guest Candle",
            "center": (1.58, 4.52),
            "size": (0.18, 0.24),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "reference_book",
            "name": "Reference Book on the Desk",
            "center": (1.80, 4.90),
            "size": (0.36, 0.28),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "tea_cup",
            "name": "Teacup",
            "center": (1.38, 4.52),
            "size": (0.16, 0.16),
            "status": "regular",
            "movable": True,
            "state_details": {"tea_state": "empty"},
        },
        {
            "node_id": "small_teapot",
            "name": "Small Teapot",
            "center": (1.86, 4.54),
            "size": (0.24, 0.20),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "green_round_rug",
            "name": "Round Green Carpet",
            "center": (1.65, 4.84),
            "size": (2.15, 1.95),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "left_wall_shelf",
            "name": "Small Potion Rack on the Left Wall",
            "center": (0.38, 4.90),
            "size": (0.28, 1.20),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "side_potion_flask",
            "name": "Left Flask",
            "center": (0.55, 4.25),
            "size": (0.26, 0.35),
            "status": "regular",
            "movable": True,
        },
    ],
    "fireplace_area": [
        {
            "node_id": "stone_fireplace",
            "name": "Stone Fireplace",
            "center": (0.94, 7.54),
            "size": (1.05, 1.12),
            "status": "regular",
            "movable": False,
            "state_details": {"fireplace_state": "low", "room_warmth": "comfortable"},
        },
        {
            "node_id": "active_fire",
            "name": "Fireplace Fire",
            "center": (0.95, 7.70),
            "size": (0.45, 0.42),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "mantel_shelf",
            "name": "Fireplace Mantel",
            "center": (0.95, 6.86),
            "size": (0.96, 0.22),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "mantel_photo",
            "name": "Fireplace Photo",
            "center": (0.74, 6.68),
            "size": (0.24, 0.24),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "firewood_stack",
            "name": "Woodpile",
            "center": (1.58, 8.62),
            "size": (0.55, 0.36),
            "status": "regular",
            "movable": True,
            "state_details": {"firewood_amount": "enough"},
        },
        {
            "node_id": "fireplace_poker",
            "name": "fire poker",
            "center": (1.72, 7.58),
            "size": (0.12, 0.62),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "ash_bucket",
            "name": "ash bucket",
            "center": (2.40, 8.72),
            "size": (0.38, 0.42),
            "status": "regular",
            "movable": False,
            "state_details": {"ash_state": "some_ash"},
        },
        {
            "node_id": "drying_herb_hook",
            "name": "herb hook",
            "center": (1.55, 6.80),
            "size": (0.24, 0.45),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "lower_wooden_door",
            "name": "lower wooden door",
            "center": (1.30, 9.08),
            "size": (0.86, 0.28),
            "status": "regular",
            "movable": False,
            "state_details": {"door_state": "closed"},
        },
        {
            "node_id": "stone_steps",
            "name": "lower stone step",
            "center": (2.35, 9.22),
            "size": (0.78, 0.36),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "broom_bundle",
            "name": "broom and herb bundle",
            "center": (1.86, 7.18),
            "size": (0.22, 0.72),
            "status": "regular",
            "movable": True,
        },
    ],
    "cleanup_area": [
        {
            "node_id": "stone_sink",
            "name": "stone sink",
            "center": (4.18, 7.32),
            "size": (0.95, 0.78),
            "status": "regular",
            "movable": False,
            "state_details": {"sink_state": "clean", "tap_state": "off"},
        },
        {
            "node_id": "copper_tap",
            "name": "brass faucet",
            "center": (4.18, 6.90),
            "size": (0.22, 0.22),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "drying_rack",
            "name": "drying rack",
            "center": (5.12, 7.14),
            "size": (0.64, 0.42),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "glassware_set_dirty",
            "name": "glassware to be cleaned",
            "center": (4.88, 6.78),
            "size": (0.46, 0.30),
            "status": "regular",
            "movable": True,
            "state_details": {"glassware_state": "dirty"},
        },
        {
            "node_id": "glassware_set_clean",
            "name": "clean glassware",
            "center": (5.42, 6.88),
            "size": (0.42, 0.28),
            "status": "regular",
            "movable": True,
            "state_details": {"glassware_state": "clean"},
        },
        {
            "node_id": "cleaning_cloth",
            "name": "cleaning cloth",
            "center": (5.26, 7.58),
            "size": (0.28, 0.18),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "cleaning_brush",
            "name": "Cleaning Brush",
            "center": (4.86, 7.78),
            "size": (0.12, 0.42),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "soap_bottle",
            "name": "Cleaning Solution Bottle",
            "center": (4.52, 6.92),
            "size": (0.16, 0.22),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "waste_liquid_bucket",
            "name": "Waste Liquid Bucket",
            "center": (4.70, 8.62),
            "size": (0.45, 0.45),
            "status": "regular",
            "movable": False,
            "state_details": {"waste_bucket_state": "half_full"},
        },
        {
            "node_id": "bottle_recycling_crate",
            "name": "Empty Bottle Recycling Bin",
            "center": (5.45, 8.78),
            "size": (0.56, 0.40),
            "status": "regular",
            "movable": False,
        },
    ],
    "potion_brewing_area": [
        {
            "node_id": "iron_cauldron",
            "name": "Iron Cauldron",
            "center": (7.20, 4.62),
            "size": (0.80, 0.80),
            "status": "regular",
            "movable": False,
            "state_details": {
                "cauldron_state": "empty",
                "potion_color": "unknown",
                "potion_stability": "stable",
                "steam_state": "none",
            },
        },
        {
            "node_id": "cauldron_stand",
            "name": "Cauldron Stand",
            "center": (7.20, 4.88),
            "size": (0.94, 0.94),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "heating_flame",
            "name": "Cauldron Flame",
            "center": (7.20, 5.10),
            "size": (0.48, 0.34),
            "status": "regular",
            "movable": False,
            "state_details": {"flame_state": "off"},
        },
        {
            "node_id": "stirring_rod",
            "name": "Stirring Rod",
            "center": (7.42, 4.45),
            "size": (0.12, 0.62),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "curved_brewing_workbench",
            "name": "Curved Potion Workbench",
            "center": (7.72, 5.72),
            "size": (2.38, 0.80),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "workbench_potion_bottles",
            "name": "Workbench Potion Bottle Set",
            "center": (6.75, 5.62),
            "size": (0.62, 0.30),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "glass_flask",
            "name": "Glass Flask",
            "center": (8.28, 4.40),
            "size": (0.26, 0.34),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "round_bottom_flask",
            "name": "Round-Bottom Flask",
            "center": (8.28, 5.38),
            "size": (0.34, 0.34),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "test_tube_rack",
            "name": "Test tube rack",
            "center": (8.58, 5.28),
            "size": (0.62, 0.30),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "brass_scale",
            "name": "Brass balance scale",
            "center": (8.82, 5.90),
            "size": (0.55, 0.36),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "mortar_and_pestle",
            "name": "Mortar and pestle",
            "center": (7.92, 5.82),
            "size": (0.40, 0.36),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "herb_cutting_board",
            "name": "Herb cutting board",
            "center": (6.72, 5.84),
            "size": (0.55, 0.38),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "small_knife",
            "name": "Small knife",
            "center": (6.62, 5.58),
            "size": (0.32, 0.08),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "measuring_spoon",
            "name": "Measuring spoon",
            "center": (6.95, 5.56),
            "size": (0.28, 0.10),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "recipe_scroll_brewing",
            "name": "Potion recipe scroll",
            "center": (8.86, 5.48),
            "size": (0.34, 0.18),
            "status": "regular",
            "movable": True,
        },
    ],
    "ingredient_storage_area": [
        {
            "node_id": "apothecary_drawer_cabinet",
            "name": "Herbal medicine drawer cabinet",
            "center": (7.02, 8.02),
            "size": (1.10, 1.42),
            "status": "regular",
            "movable": False,
            "state_details": {"inventory_state": "normal"},
        },
        {
            "node_id": "glass_jar_shelf",
            "name": "Glass jar rack",
            "center": (8.52, 7.82),
            "size": (1.08, 1.30),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "rare_ingredient_cabinet",
            "name": "Rare materials cabinet",
            "center": (8.48, 9.08),
            "size": (0.98, 0.78),
            "status": "regular",
            "movable": False,
            "state_details": {"rare_cabinet_state": "locked", "dangerous_item_access": "denied"},
        },
        {
            "node_id": "herb_bundle_dried",
            "name": "Bundle of dried herbs",
            "center": (6.44, 7.12),
            "size": (0.22, 0.44),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "root_sample_jar",
            "name": "Root specimen jar",
            "center": (6.55, 8.82),
            "size": (0.25, 0.34),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "powder_bone_jar",
            "name": "Bone Meal Jar",
            "center": (6.90, 8.86),
            "size": (0.25, 0.34),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "crystal_shard_bottle",
            "name": "Crystal Shard Bottle",
            "center": (7.25, 8.88),
            "size": (0.24, 0.34),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "insect_specimen_bottle",
            "name": "Insect Specimen Jar",
            "center": (8.26, 7.28),
            "size": (0.24, 0.34),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "mushroom_box",
            "name": "Mushroom Box",
            "center": (7.72, 9.30),
            "size": (0.42, 0.34),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "label_tag",
            "name": "Material Label",
            "center": (7.52, 7.35),
            "size": (0.18, 0.12),
            "status": "regular",
            "movable": True,
            "state_details": {"label_state": "clear"},
        },
        {
            "node_id": "cabinet_key",
            "name": "Cabinet Key",
            "center": (6.45, 8.28),
            "size": (0.14, 0.08),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "inventory_scroll",
            "name": "Inventory Scroll",
            "center": (6.75, 8.35),
            "size": (0.32, 0.18),
            "status": "regular",
            "movable": True,
        },
        {
            "node_id": "lower_bottle_crate",
            "name": "Lower Potion Chest",
            "center": (7.78, 9.55),
            "size": (0.72, 0.30),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "bottom_alchemy_table",
            "name": "Bottom Small Alchemy Table",
            "center": (6.55, 9.38),
            "size": (0.65, 0.36),
            "status": "regular",
            "movable": False,
        },
        {
            "node_id": "large_corner_plant",
            "name": "Large Plant in Bottom Right Corner",
            "center": (8.92, 9.18),
            "size": (0.55, 0.62),
            "status": "regular",
            "movable": False,
            "state_details": {"plant_state": "healthy"},
        },
    ],
}


POTIONS_TEACHER_OFFICE_BLOCKING_ELEMENT_IDS = {
    "heavy_wooden_door",
    "robe_rack",
    "small_drawer_entry",
    "large_wooden_desk",
    "high_back_chair",
    "desk_drawer_left",
    "desk_drawer_right",
    "gothic_window",
    "window_sill_plants",
    "potion_diagram_frame",
    "alchemy_symbol_chart",
    "curved_display_shelf",
    "hanging_scale",
    "magical_potted_plant",
    "round_consult_table",
    "guest_chair_a",
    "guest_chair_b",
    "left_wall_shelf",
    "stone_fireplace",
    "active_fire",
    "mantel_shelf",
    "ash_bucket",
    "drying_herb_hook",
    "lower_wooden_door",
    "stone_steps",
    "stone_sink",
    "copper_tap",
    "drying_rack",
    "waste_liquid_bucket",
    "bottle_recycling_crate",
    "iron_cauldron",
    "cauldron_stand",
    "heating_flame",
    "curved_brewing_workbench",
    "test_tube_rack",
    "apothecary_drawer_cabinet",
    "glass_jar_shelf",
    "rare_ingredient_cabinet",
    "lower_bottle_crate",
    "bottom_alchemy_table",
    "large_corner_plant",
}
